name: MacOS Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          
      - name: GitHub Tag
        run: | 
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"

      - name: Setup + Build + Zip
        run: |
          # replace the pyqt requirements in pyproject.toml
          sed -i '' 's/pyqt5-qt5==/pyqt5-qt5>=/' pyproject.toml

          echo "Venv setup"
          python -m venv .venv
          source ./.venv/bin/activate
          
          echo "Installing dependencies"
          pip install -e ./
          
          echo "Building style"
          python build_style.py
          
          echo "Building application"
          cd scripts
          bash build_mac.sh
          
          echo "Zipping to Blender_Launcher_${{ github.ref_name }}_macos_arm64.zip"
          cd ../dist/release
          # this zips just like the one in finder
          ditto -c -k --sequesterRsrc --keepParent "Blender Launcher.app" "Blender_Launcher_${{ github.ref_name }}_macos_arm64.zip"
          mv "Blender_Launcher_${{ github.ref_name }}_macos_arm64.zip" ../..
          cd ../..

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./Blender_Launcher_${{  github.ref_name }}_macos_arm64.zip
